version: '3.8'

services:
  app:
    container_name: next-boilerplate-app        #🔎 Fix name "next-boilerplate-app"
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    ports:
      - "3000:3000"
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - node_modules:/app/node_modules

networks:
  app_network:
    driver: bridge

volumes:
  node_modules: