import type { Metadata } from "next";

import dynamic from "next/dynamic";
import localFont from "next/font/local";

import "./globals.css";
import { Providers } from "../providers/providers";

const Navbar = dynamic(() => import("@/components/navbar"), {
  ssr: false, // Disable server-side rendering for this component
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
};

export default async function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} font-sans antialiased`}>
        <Providers>
          <Navbar />
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
